name: nudger
description: Nudger keeps Oracle ATP DB active by sending it lightweight queries regulary to prevent automatic instance shutdown due to inactivity.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dart_odbc: ^4.1.2+1
  logging: ^1.3.0

dev_dependencies:
  very_good_analysis: ^6.0.0
